function [ eigenVals, eigenVecs ] = eigenCollector( i_version )
% This function calculates the eigenvalues and eigenvectors from a
% particular inertiaTensorCollection file generated by the
% 'tensorCollector.m' script. 
%  
%   This function takes as input a string containing the version number for
%   the desired inertiaTensorCollection, e.g. like the 'version' varible
%   below:
%    movieName = strcat('r1');
%    version = strcat(movieName, '_v2');
%
%   This function outputs the collection of eigenvalues and eigenvectors
%   for all cells and frames of the movie from which
%   inertiaTensorCollection_version was created. It also saves a file
%   containing the same data and with the same version as used to create it. 

    % Load the appropriate inertiaTensorCollection:
      inertiaTensorCollection = load(strcat('InertiaTensorCollection_', i_version, '.mat'));
%     inertiaTensorCollection = load(strcat('/Users/stephenwedekind/Dropbox/School/RESEARCH/Loerke_group/Cell_Measurement/InertiaTensor/InertiaTensorCollection_', i_version, '.mat'));

    % Get numbers of frames and cells to use as limits in subsequent loops: 
    numFrames = size(inertiaTensorCollection.inertiaTensorCollection, 1);
    numCells = size(inertiaTensorCollection.inertiaTensorCollection{end,1}, 1);
    
    % Prepare containers for results:
    % theta_vs_time = NaN(length(thetas), numFrames, 2);
    eigenVals = NaN(numCells, numFrames, 2);
    eigenVecs = cell(numCells, numFrames);

    for frameNum = 1:numFrames
        for cellNum = 1:size(inertiaTensorCollection.inertiaTensorCollection{frameNum,1}, 1)
            tensor = inertiaTensorCollection.inertiaTensorCollection{frameNum,1}(cellNum);
            
            % Sanity check to ensure 'tensor' is not empty:
            if isempty(tensor)
                disp('stuff')
            end
            
            % Compute eigenvalues and eigenvectors:
            %%% D is a diagonal matrix whose diagonal elements are the eigenvalues
            %%% V is a matrix whose columns are the eigenvectors
            [V,D] = eig(tensor{1});
            
            % Next two lines sort eigenVals and Vecs https://scicomp.stackexchange.com/questions/2824/ordering-of-eigenvalues-and-eigenvectors-in-matlab
            [~,permutation]=sort(diag(D));
            D=D(permutation,permutation);V=V(:,permutation);
            
            % Organize these eigenvalues and eigenvectors according to cell
            % and frame:
            eigenVals(cellNum, frameNum, 1) = D(1,1);
            eigenVals(cellNum, frameNum, 2) = D(2,2);
            eigenVecs{cellNum, frameNum} = V;

        end
    end
    
    % Save results:
    filename = strcat('eigenValsVecs_', i_version, '.mat');
    save(filename, 'eigenVals', 'eigenVecs');
    
end